<a href="https://colab.research.google.com/github/GraphicsLan/Medical-Data-Visualizer/blob/main/Bsgroupings2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:

up = pd.read_excel('/content/bsreg2025.xlsx', sheet_name="Upschool")

In [ ]:
up.head()

,Full Name,Phone Number,Gender,Year & Semester,Halls_2,Halls,Pastor
0,Gerald Ogwindi,700714032,Male,Y2S2,Up,"Upschool (Mama Ngina, Barret, Uganda, Ruwenzor...",No
1,Alali Newton Toboso,704967181,Male,Y4S2,Up,"Upschool (Mama Ngina, Barret, Uganda, Ruwenzor...",No
2,CHARLES MUSYOKI,799447490,Male,Y1S2,Up,"Upschool (Mama Ngina, Barret, Uganda, Ruwenzor...",Yes
3,Clinton Abuga Joseph,723651634,Male,Y2S2,Up,"Upschool (Mama Ngina, Barret, Uganda, Ruwenzor...",No
4,Abigael Musangi Mueke,713249768,Female,Y4S2,Up,"Upschool (Mama Ngina, Barret, Uganda, Ruwenzor...",No

In [ ]:
up.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Full Name          50 non-null     object
 1   Phone Number       50 non-null     object
 2   Gender             50 non-null     object
 3   Year & Semester    50 non-null     object
 4   Areas around gate  50 non-null     object
 5    Pastor            50 non-null     object
dtypes: object(6)
memory usage: 2.5+ KB

In [ ]:
up.tail()

,Full Name,Phone Number,Gender,Year & Semester,Areas around gate,Pastor
45,Kapolon Mevline,782372505,Female,Y2S2,Jacaranda,No
46,Macklester Mudoga,768684189,Male,Y3S2,Booster,No
47,Purity Akinyi,718093560,Female,Y3S2,Booster,No
48,Casper Kelly Okuku,740654363,Male,Y2S2,Booster,No
49,Tabitha Wambui Kamweru,746097736,Female,Y5S2,Booster,yes

In [ ]:
up.describe()

,Full Name,Phone Number,Gender,Year & Semester,Halls_2,Halls,Pastor
count,145,145,145,145,145,145,145
unique,131,131,2,5,1,1,2
top,Stanley otieno,704062156,Female,Y1S2,Up,"Upschool (Mama Ngina, Barret, Uganda, Ruwenzor...",No
freq,3,3,85,65,145,145,115

In [ ]:
num_groups = 29

In [ ]:
# Shuffle the dataset
up = up.sample(frac=1, random_state=42).reset_index(drop=True)

# Assign equal-sized groups
up['Group'] = up.index % num_groups + 1

# Preview the grouped dataset
up

,Full Name,Phone Number,Gender,Year & Semester,Halls_2,Halls,Pastor,Group
0,Kiplimo Victoria Jebet,113272487,Female,Any other,Up,"Upschool (Mama Ngina, Barret, Uganda, Ruwenzor...",No,1
1,Silveria,798401556,Female,Y1S2,Up,"Upschool (Mama Ngina, Barret, Uganda, Ruwenzor...",No,2
2,Loreen Oyaya,792501986,Female,Y4S2,Up,"Upschool (Mama Ngina, Barret, Uganda, Ruwenzor...",No,3
3,Gideon Mbevo,792248751,Male,Y1S2,Up,"Upschool (Mama Ngina, Barret, Uganda, Ruwenzor...",No,4
4,Samuel Kimanzi,710211282,Male,Y1S2,Up,"Upschool (Mama Ngina, Barret, Uganda, Ruwenzor...",No,5
...,...,...,...,...,...,...,...,...
140,Patrick Maina muthoni,798540722,Male,Y1S2,Up,"Upschool (Mama Ngina, Barret, Uganda, Ruwenzor...",No,25
141,Grace Ndinda Maweu,793909317,Female,Y1S2,Up,"Upschool (Mama Ngina, Barret, Uganda, Ruwenzor...",No,26
142,Monica Akuyen Lorukia,710632209,Female,Y1S2,Up,"Upschool (Mama Ngina, Barret, Uganda, Ruwenzor...",No,27
143,Wanambisi Reinhard Imbwaga,115248482,Male,Y3S2,Up,"Upschool (Mama Ngina, Barret, Uganda, Ruwenzor...",No,28
144,Sharlyne nzilani singu,797782787,Female,Y1S2,Up,"Upschool (Mama Ngina, Barret, Uganda, Ruwenzor...",No,29

In [ ]:
# Define the sample size per group
sample_size = 5 # Choose 2 samples per group

# Randomly sample from each group
equal_samples = up.groupby('Group').sample(n=sample_size, random_state=42)

# Display result
equal_samples

,Full Name,Phone Number,Gender,Year & Semester,Halls_2,Halls,Pastor,Group
29,Angelo Njuguna,702444048,Male,Y1S2,Up,"Upschool (Mama Ngina, Barret, Uganda, Ruwenzor...",No,1
116,Audrey Anne Otieno,784695591,Female,Y1S2,Up,"Upschool (Mama Ngina, Barret, Uganda, Ruwenzor...",No,1
58,Stanley otieno,717199593,Male,Y1S2,Up,"Upschool (Mama Ngina, Barret, Uganda, Ruwenzor...",No,1
0,Kiplimo Victoria Jebet,113272487,Female,Any other,Up,"Upschool (Mama Ngina, Barret, Uganda, Ruwenzor...",No,1
87,Monica waithera,111464152,Female,Y1S2,Up,"Upschool (Mama Ngina, Barret, Uganda, Ruwenzor...",Yes,1
...,...,...,...,...,...,...,...,...
57,Duncan Cherono,113366460,Male,Y1S2,Up,"Upschool (Mama Ngina, Barret, Uganda, Ruwenzor...",No,29
144,Sharlyne nzilani singu,797782787,Female,Y1S2,Up,"Upschool (Mama Ngina, Barret, Uganda, Ruwenzor...",No,29
86,Ivy cherono,727232645,Female,Y1S2,Up,"Upschool (Mama Ngina, Barret, Uganda, Ruwenzor...",No,29
115,Wendy Whitney,793805357,Female,Y3S2,Up,"Upschool (Mama Ngina, Barret, Uganda, Ruwenzor...",No,29
28,Lewa Emmanuel Beja,795225898,Male,Y4S2,Up,"Upschool (Mama Ngina, Barret, Uganda, Ruwenzor...",No,29

In [ ]:
pd.value_counts(equal_samples['Group'])

<ipython-input-141-81ffe7df5d84>:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(equal_samples['Group'])

Group
1     5
16    5
28    5
27    5
26    5
25    5
24    5
23    5
22    5
21    5
20    5
19    5
18    5
17    5
15    5
2     5
14    5
13    5
12    5
11    5
10    5
9     5
8     5
7     5
6     5
5     5
4     5
3     5
29    5
Name: count, dtype: int64

In [ ]:
equal_samples.to_csv('Upschool_grouped.csv', index=False)